version: "3"

services:
  server:
    container_name: app-play-server
    image: node:alpine
    volumes:
      - ./server:/app-server
    working_dir: /app-server
    environment:
      NODE_ENV: development
    ports:
      - 4444:4444
    command: node server.js

  core:
    container_name: app-play-core
    build: ./core/
    volumes:
      - ./core://home/node/app/
    working_dir: /home/node/app/
    ports:
      - 6666:6666
    command: /bin/sh -c "pm2 start core.js && pm2 logs"

  nginx:
    container_name: app-play-nginx
    image: nginx:1.13.12-alpine
    ports:
    - "8888:80"
    - "4443:443"
    environment:
    - NGINX_PORT=80
    volumes:
    - ./client:/usr/share/nginx/html